# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BertTokenClassifier": "00_bert_token_classifier.ipynb"}

modules = ["bert/experiments/bert_token_classifier.py",
           "bert_experiments/bert_token_classifier.py"]

doc_url = "https://adamjankaczmarek.github.io/wimlds_nbdev_template/"

git_url = "https://github.com/adamjankaczmarek/wimlds_nbdev_template/tree/master/"

def custom_doc_links(name): return None
